services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: hack_web
    networks:
      - hack-network-web

  nginx:
    image: nginx:1.25
    container_name: hack_nginx
    volumes:
      - type: bind
        source: ./nginx/conf/dev.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true

      - ./nginx/logs:/var/log/nginx/
    ports:
      - "12800:80"
    depends_on:
      - web
    networks:
      - hack-network-web

networks:
  hack-network-web:
    driver: bridge
