# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: .env
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.12.0]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
    - run: npm ci
      working-directory: ./web
    - run: npm run build --if-present
      working-directory: ./web
    # - run: npm test
    #   working-directory: ./web
      env:
        MONGODB_PW: ${{ secrets.MONGODB_PW }}
        MONGODB_USER: ${{ secrets.MONGODB_USER }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        BASEPATH: ${{ vars.BASE_PATH }}
